name: Check

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Go Build & Vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod
          cache-dependency-path: server/go.sum

      - name: Build
        run: CGO_ENABLED=1 go build -C server ./...

      - name: Vet
        run: go vet -C server ./...

      - name: Log success
        run: echo "✅ Success!"
