name: Check

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Go Build & Vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mesahub-mono
        uses: actions/checkout@v4
        with:
          repository: mesahub-db/mesahub-mono
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: core/server/go.mod
          cache-dependency-path: |
            core/server/go.sum
            cloud/server/go.sum

      - name: Build core server
        run: |
          CGO_ENABLED=1 go build -C core/server ./...

      - name: Vet
        run: |
          go vet -C core/server ./...

      - name: Log success
        run: echo "✅ Success!"
